---
language: python
services:
  - docker

env:
  global:
    - ROLE_NAME: ovirt.engine-ldap
    - GALAXY_ROLE_NAME: jobcespedes.ovirt.engine-ldap
  matrix:
    - MOLECULE_DISTRO: centos7

before_install: "./test/scripts/before-install.sh"
install: "./test/scripts/install.sh"
script: "./test/scripts/test-role.sh"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
